### ISSUE TITLE
Broadcasting?

### ISSUE THREAD

**Issue by stephanembl** [imanel/websocket-rack#16]
Hi!

This gem doesn't seem to handle broadcasting to all clients. Am I right?

Thanks.

**Comment by imanel** [comment]
There is no 'broadcast' method by default, but it's easy to implement it by yourself depending on requirements:

```
class MyApp < Rack::WebSocket::Application
  def self.clients
    @clients ||= Set.new
  end

  def on_open(env)
    self.class.clients.add(self)
  end

  def on_message(env, msg)
    self.class.clients.each do |client|
      client.send_data(msg) unless client == self
    end
  end

  def on_close(env)
    self.class.clients.delete(self)
  end
end
```

The reason for not implementing it is that each application have different requirements: some need sending to every client, some exclude themselves (see example above) and some sends only to specific groups.
